function im = noiseModel()
a=imread('a.tif');
b=imread('b.tif');
c=imread('c.tif');
d=imread('d.tif');
e=imread('e.tif');
f=imread('f.tif');
figure
subplot(2,3,1);
imshow(a);
title('Guassian');
subplot(2,3,2);
imshow(b);
title('Rayleigh');
subplot(2,3,3);
imshow(c);
title('Erlang');
subplot(2,3,4);
imshow(d);
title('Exponential');
subplot(2,3,5);
imshow(e);
title('Uniform');
subplot(2,3,6);
imshow(f);
title('Impulse');
figure
subplot(2,3,1);
imhist(a);
title('Guassian');
subplot(2,3,2);
imhist(b);
title('Rayleigh');
subplot(2,3,3);
imhist(c);
title('Erlang');
subplot(2,3,4);
imhist(d);
title('Exponential');
subplot(2,3,5);
imhist(e);
title('Uniform');
subplot(2,3,6);
imhist(f);
title('Impulse');
end